version: "3"
services: 
  db:
    image: postgres
    container_name: "pokestats_container"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pokemon_stats

    ports:
      - "5432:5432"
    volumes:
      - "./db:/var/lib/postgresql/data/"
      - "./scripts:/docker-entrypoint-initdb.d/"